#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

nTarget = 4000000

nFibCurrent = 1
nFibPrevious = 0
nAux = 0
nResult = 0
nCount = 1
sSum = 'N'

while nFibCurrent < nTarget:
    nAux = nFibCurrent
    nFibCurrent = nFibCurrent + nFibPrevious
    nFibPrevious = nAux
    if nFibCurrent % 2 == 0:
        nResult = nResult + nFibCurrent
        sSum = 'Y'
    print( nCount, nFibCurrent, nResult, sSum )
    nCount = nCount + 1
    sSum = 'N'
print( nResult )


